ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ kg.automoika.ApplicationKt.module ]
    }
    mongo {
        uri = "mongodb+srv://flay:3tnXuYZbkHL0bGH2@clustercarwash.fn4om.mongodb.net/?retryWrites=true&w=majority&appName=ClusterCarWash$"
        database = "CarWashDatabase"
    }
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcURL = "jdbc:postgresql://localhost:5432/automoika-db?currentSchema=car-washes"
    user = "postgres"
    password = "rysbek123"
}

firebase {
    adminSdkFilePath = "/Users/test/Documents/Projects/AutomoikaNew/src/main/resources/firebase-admin-sdk.json"
    serverAdminSdkFilePath = "/root/Automoika-Kg/firebase-admin-sdk.json"
    accountId = "firebase-adminsdk-fbsvc@automoika-kg-android.iam.gserviceaccount.com"
    url = "https://tam-tam-8b2a7-default-rtdb.firebaseio.com"
}
yandex {
    geoCodeUrl = "https://geocode-maps.yandex.ru/v1/"
    geoCodeApiKey = "e80d0a32-f953-433a-9abc-e0c057387e31"
}

